// <auto-generated />
using System;
using CourierJobService.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CourierJobService.Migrations
{
    [DbContext(typeof(CourierJobDbContext))]
    [Migration("20260526133343_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CourierJobService.Database.Bidding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("CustomClearanceCharges")
                        .HasColumnType("float");

                    b.Property<double?>("HandlingCharges")
                        .HasColumnType("float");

                    b.Property<bool?>("IsInsurancePolicy")
                        .HasColumnType("bit");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<int?>("JobStatusId")
                        .HasColumnType("int");

                    b.Property<double?>("PickupCharges")
                        .HasColumnType("float");

                    b.Property<double>("TotalAmount")
                        .HasColumnType("float");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("JobStatusId");

                    b.HasIndex(new[] { "UserId", "JobId" }, "UK_Biddings")
                        .IsUnique();

                    b.ToTable("Biddings");
                });

            modelBuilder.Entity("CourierJobService.Database.BiddingCharge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("Amount")
                        .HasColumnType("float");

                    b.Property<int?>("BiddingId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("BiddingId");

                    b.ToTable("BiddingCharges");
                });

            modelBuilder.Entity("CourierJobService.Database.BiddingProposal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BiddingId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeliveryDateUtc")
                        .HasColumnType("datetime");

                    b.Property<int?>("DeliveryTypeId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsBaseBid")
                        .HasColumnType("bit");

                    b.Property<double?>("Total")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("BiddingId");

                    b.HasIndex("DeliveryTypeId");

                    b.ToTable("BiddingProposals");
                });

            modelBuilder.Entity("CourierJobService.Database.BiddingProposalItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BiddingProposalId")
                        .HasColumnType("int");

                    b.Property<double?>("ItemTotal")
                        .HasColumnType("float");

                    b.Property<int?>("JobItemId")
                        .HasColumnType("int");

                    b.Property<double?>("UnitPrice")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("BiddingProposalId");

                    b.HasIndex("JobItemId");

                    b.ToTable("BiddingProposalItems");
                });

            modelBuilder.Entity("CourierJobService.Database.CargoMode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.ToTable("CargoModes");
                });

            modelBuilder.Entity("CourierJobService.Database.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("CourierJobService.Database.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("CourierJobService.Database.CourierMode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.ToTable("CourierModes");
                });

            modelBuilder.Entity("CourierJobService.Database.DeliveryType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("NoOfDays")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_DeliveryOptions");

                    b.ToTable("DeliveryTypes");
                });

            modelBuilder.Entity("CourierJobService.Database.ItemType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ItemTypes");
                });

            modelBuilder.Entity("CourierJobService.Database.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CargoModeId")
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("CourierModeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOnUtc")
                        .HasColumnType("datetime");

                    b.Property<string>("DestinationAddress")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("DestinationCityId")
                        .HasColumnType("int");

                    b.Property<int?>("DestinationCountryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpiryDateUtc")
                        .HasColumnType("datetime");

                    b.Property<bool?>("IsJobStatusFromBid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("JobNumber")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("JobStatusId")
                        .HasColumnType("int");

                    b.Property<string>("OriginAddress")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("OriginCityId")
                        .HasColumnType("int");

                    b.Property<int?>("OriginCountryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PickupDateUtc")
                        .HasColumnType("datetime");

                    b.Property<string>("RecipientContact")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("RecipientEmail")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("RecipientName")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CargoModeId");

                    b.HasIndex("CourierModeId");

                    b.HasIndex("DestinationCityId");

                    b.HasIndex("DestinationCountryId");

                    b.HasIndex("JobStatusId");

                    b.HasIndex("OriginCityId");

                    b.HasIndex("OriginCountryId");

                    b.HasIndex(new[] { "JobNumber" }, "IX_Jobs")
                        .IsUnique()
                        .HasFilter("[JobNumber] IS NOT NULL");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("CourierJobService.Database.JobItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("DeclaredValue")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Dimensions")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<int?>("ItemTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("JobId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<double?>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ItemTypeId");

                    b.HasIndex("JobId");

                    b.ToTable("JobItems");
                });

            modelBuilder.Entity("CourierJobService.Database.JobItemImage", b =>
                {
                    b.Property<int>("JobItemId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("JobItemId")
                        .HasName("PK__JobItemI__A65D44637E33E7C7");

                    b.ToTable("JobItemImages");
                });

            modelBuilder.Entity("CourierJobService.Database.JobStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("JobStatuses");
                });

            modelBuilder.Entity("CourierJobService.Database.Bidding", b =>
                {
                    b.HasOne("CourierJobService.Database.Job", "Job")
                        .WithMany("Biddings")
                        .HasForeignKey("JobId")
                        .IsRequired()
                        .HasConstraintName("FK_Biddings_Jobs");

                    b.HasOne("CourierJobService.Database.JobStatus", "JobStatus")
                        .WithMany("Biddings")
                        .HasForeignKey("JobStatusId")
                        .HasConstraintName("FK_Biddings_JobStatuses");

                    b.Navigation("Job");

                    b.Navigation("JobStatus");
                });

            modelBuilder.Entity("CourierJobService.Database.BiddingCharge", b =>
                {
                    b.HasOne("CourierJobService.Database.Bidding", "Bidding")
                        .WithMany("BiddingCharges")
                        .HasForeignKey("BiddingId")
                        .HasConstraintName("FK_BiddingCharges_Biddings");

                    b.Navigation("Bidding");
                });

            modelBuilder.Entity("CourierJobService.Database.BiddingProposal", b =>
                {
                    b.HasOne("CourierJobService.Database.Bidding", "Bidding")
                        .WithMany("BiddingProposals")
                        .HasForeignKey("BiddingId")
                        .HasConstraintName("FK_BiddingProposals_Biddings");

                    b.HasOne("CourierJobService.Database.DeliveryType", "DeliveryType")
                        .WithMany("BiddingProposals")
                        .HasForeignKey("DeliveryTypeId")
                        .HasConstraintName("FK_BiddingProposals_DeliveryTypes");

                    b.Navigation("Bidding");

                    b.Navigation("DeliveryType");
                });

            modelBuilder.Entity("CourierJobService.Database.BiddingProposalItem", b =>
                {
                    b.HasOne("CourierJobService.Database.BiddingProposal", "BiddingProposal")
                        .WithMany("BiddingProposalItems")
                        .HasForeignKey("BiddingProposalId")
                        .HasConstraintName("FK_BiddingProposalItems_BiddingProposals");

                    b.HasOne("CourierJobService.Database.JobItem", "JobItem")
                        .WithMany("BiddingProposalItems")
                        .HasForeignKey("JobItemId")
                        .HasConstraintName("FK_BiddingProposalItems_JobItems");

                    b.Navigation("BiddingProposal");

                    b.Navigation("JobItem");
                });

            modelBuilder.Entity("CourierJobService.Database.City", b =>
                {
                    b.HasOne("CourierJobService.Database.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .IsRequired()
                        .HasConstraintName("FK_Cities_Countries");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("CourierJobService.Database.Job", b =>
                {
                    b.HasOne("CourierJobService.Database.CargoMode", "CargoMode")
                        .WithMany("Jobs")
                        .HasForeignKey("CargoModeId")
                        .HasConstraintName("FK_Jobs_CargoModes");

                    b.HasOne("CourierJobService.Database.CourierMode", "CourierMode")
                        .WithMany("Jobs")
                        .HasForeignKey("CourierModeId")
                        .HasConstraintName("FK_Jobs_CourierModes");

                    b.HasOne("CourierJobService.Database.City", "DestinationCity")
                        .WithMany("JobDestinationCities")
                        .HasForeignKey("DestinationCityId")
                        .HasConstraintName("FK_Jobs_Cities1");

                    b.HasOne("CourierJobService.Database.Country", "DestinationCountry")
                        .WithMany("JobDestinationCountries")
                        .HasForeignKey("DestinationCountryId")
                        .HasConstraintName("FK_Jobs_Countries1");

                    b.HasOne("CourierJobService.Database.JobStatus", "JobStatus")
                        .WithMany("Jobs")
                        .HasForeignKey("JobStatusId")
                        .HasConstraintName("FK_Jobs_JobStatuses");

                    b.HasOne("CourierJobService.Database.City", "OriginCity")
                        .WithMany("JobOriginCities")
                        .HasForeignKey("OriginCityId")
                        .HasConstraintName("FK_Jobs_Cities");

                    b.HasOne("CourierJobService.Database.Country", "OriginCountry")
                        .WithMany("JobOriginCountries")
                        .HasForeignKey("OriginCountryId")
                        .HasConstraintName("FK_Jobs_Countries");

                    b.Navigation("CargoMode");

                    b.Navigation("CourierMode");

                    b.Navigation("DestinationCity");

                    b.Navigation("DestinationCountry");

                    b.Navigation("JobStatus");

                    b.Navigation("OriginCity");

                    b.Navigation("OriginCountry");
                });

            modelBuilder.Entity("CourierJobService.Database.JobItem", b =>
                {
                    b.HasOne("CourierJobService.Database.ItemType", "ItemType")
                        .WithMany("JobItems")
                        .HasForeignKey("ItemTypeId")
                        .HasConstraintName("FK_JobItems_ItemTypes");

                    b.HasOne("CourierJobService.Database.Job", "Job")
                        .WithMany("JobItems")
                        .HasForeignKey("JobId")
                        .HasConstraintName("FK_JobItems_Jobs");

                    b.Navigation("ItemType");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("CourierJobService.Database.JobItemImage", b =>
                {
                    b.HasOne("CourierJobService.Database.JobItem", "JobItem")
                        .WithOne("JobItemImage")
                        .HasForeignKey("CourierJobService.Database.JobItemImage", "JobItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_JobItemImage_JobItem");

                    b.Navigation("JobItem");
                });

            modelBuilder.Entity("CourierJobService.Database.Bidding", b =>
                {
                    b.Navigation("BiddingCharges");

                    b.Navigation("BiddingProposals");
                });

            modelBuilder.Entity("CourierJobService.Database.BiddingProposal", b =>
                {
                    b.Navigation("BiddingProposalItems");
                });

            modelBuilder.Entity("CourierJobService.Database.CargoMode", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("CourierJobService.Database.City", b =>
                {
                    b.Navigation("JobDestinationCities");

                    b.Navigation("JobOriginCities");
                });

            modelBuilder.Entity("CourierJobService.Database.Country", b =>
                {
                    b.Navigation("Cities");

                    b.Navigation("JobDestinationCountries");

                    b.Navigation("JobOriginCountries");
                });

            modelBuilder.Entity("CourierJobService.Database.CourierMode", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("CourierJobService.Database.DeliveryType", b =>
                {
                    b.Navigation("BiddingProposals");
                });

            modelBuilder.Entity("CourierJobService.Database.ItemType", b =>
                {
                    b.Navigation("JobItems");
                });

            modelBuilder.Entity("CourierJobService.Database.Job", b =>
                {
                    b.Navigation("Biddings");

                    b.Navigation("JobItems");
                });

            modelBuilder.Entity("CourierJobService.Database.JobItem", b =>
                {
                    b.Navigation("BiddingProposalItems");

                    b.Navigation("JobItemImage");
                });

            modelBuilder.Entity("CourierJobService.Database.JobStatus", b =>
                {
                    b.Navigation("Biddings");

                    b.Navigation("Jobs");
                });
#pragma warning restore 612, 618
        }
    }
}
