version: '3.4'

networks:
  backend:
  

services:

  ocelotapigw:
    container_name: api-gateway
    image: ${DOCKER_REGISTRY-}ocelotapigw
    build:
      context: .
      dockerfile: OcelotApiGw/Dockerfile
    ports:
    - 61260:8080
    networks:
    - backend


  tranxitdb:
    container_name: tranxit-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
     - 1433:1433
    environment:
    - ACCEPT_EULA=Y
    - MSSQL_SA_PASSWORD=Hamza_1234
    volumes:
    - ./.containers/database/data:/var/opt/mssql/data
    networks:
    - backend

  accountservice:
    container_name: account-service
    image: ${DOCKER_REGISTRY-}accountservice
    build:
      context: .
      dockerfile: AccountService/Dockerfile
    depends_on:
    - tranxitdb
    networks:
    - backend


  # emailmq:
  #   image: rabbitmq:3-management
  #   container_name: email-mq
  #   hostname: emailmq
  #   volumes:
  #       - ./.containers/queue/data/:/var/lib/rabbitmq
  #       - ./.containers/queue/log/:/var/log/rabbitmq
  #   ports:
  #     - 5672:5672
  #     - 15672:15672
  #   environment:
  #       RABBITMQ_DEFAULT_USER: tranxit
  #       RABBITMQ_DEFAULT_PASS: tranxit
