version: '3.4'
networks:
  backend:
    driver: bridge

services:
  ocelotapigw:
    image: api-gateway-image
    build:
      context: .
      dockerfile: OcelotApiGw/Dockerfile
    ports:
    - 61260:8080
    networks:
    - backend

  accountservice:
    image: account-service-image
    build:
      context: .
      dockerfile: AccountService/Dockerfile
    environment:
      - RabbitMQ__HostName=rabbitmq
    networks:
    - backend
    depends_on:
      - rabbitmq


  courierjobservice:
    image: courierjob-sevice-image
    build:
      context: .
      dockerfile: CourierJobService/Dockerfile
    environment:
      - RabbitMQ__HostName=rabbitmq
    networks:
    - backend
    depends_on:
      - rabbitmq

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend
